### ISSUE TITLE
Add Tests for Brain_Data Class

### ISSUE THREAD

**Issue by ljchang** [ljchang/neurolearn#24]
Need to add more tests for all of the new Brain_Data methods.  See the <a href=https://github.com/ljchang/neurolearn/blob/master/scripts/NLTools_Brain_Data_Class_Tutorial.ipynb>ipython notebook</a> for examples of how to use all of the new methods.

**Comment by ljchang** [comment]
@samjgrey3 if you get bored over break, it might be nice to have you play around with the new Brain_Data class and see what you think.  I'm finding it pretty handy as a tool for general data manipulation and analysis.  I think it's much more intuitive to use then dealing with separate analysis classes.  Though we will still retain most of those. 

Feel free to add more pytests for the new methods I've added.  I haven't gotten around to it yet.

**Comment by samjgrey3** [comment]
Will do! I have about 10 more days before I fly home - I'll check it out then. Sounds like you're making some real progress. What prediction algorithms to we have support for now?
