### ISSUE TITLE
Brain_Data.bootstrap() Not working

### ISSUE THREAD

**Issue by ljchang** [ljchang/neurolearn#26]
Here is the command:
out2 = dat.bootstrap(analysis_type='regress',n_samples=n_samples)

Here is the error:
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-22-1d44d97b6571> in <module>()
     10 # Bootstrap Regress
     11 tic2 = time.time() #Start Timer
---> 12 out2 = dat.bootstrap(analysis_type='regress',n_samples=n_samples)
     13 toc = time.time()
     14 print 'Bootstrap Regress Time: %.2f seconds' % (toc - tic2) #Stop timer

/usr/local/lib/python2.7/site-packages/nltools-0.2-py2.7.egg/nltools/data.pyc in bootstrap(self, analysis_type, n_samples, save_weights, **kwargs)
    619                     # Aggegate bootstraps for each beta separately
    620                     for i, b in enumerate(beta.iterkeys()):
--> 621                         beta[b]=beta[b].append(out['beta'][i])
    622                 elif analysis_type is 'predict':
    623                     if 'algorithm' in kwargs:

/usr/local/lib/python2.7/site-packages/nltools-0.2-py2.7.egg/nltools/data.pyc in __getitem__(self, index)
    121             new.data = np.array(self.data[index,:])
    122         if not self.Y.empty:
--> 123             new.Y = self.Y.loc[index]
    124         if self.X.size:
    125             if isinstance(self.X,pd.DataFrame):

/usr/local/lib/python2.7/site-packages/pandas/core/indexing.pyc in __getitem__(self, key)
   1225             return self._getitem_tuple(key)
   1226         else:
-> 1227             return self._getitem_axis(key, axis=0)
   1228 
   1229     def _getitem_axis(self, key, axis=0):

/usr/local/lib/python2.7/site-packages/pandas/core/indexing.pyc in _getitem_axis(self, key, axis)
   1369 
   1370         # fall thru to straight lookup
-> 1371         self._has_valid_type(key, axis)
   1372         return self._get_label(key, axis=axis)
   1373 

/usr/local/lib/python2.7/site-packages/pandas/core/indexing.pyc in _has_valid_type(self, key, axis)
   1331                 raise
   1332             except:
-> 1333                 error()
   1334 
   1335         return True

/usr/local/lib/python2.7/site-packages/pandas/core/indexing.pyc in error()
   1318                         "cannot use label indexing with a null key")
   1319                 raise KeyError("the label [%s] is not in the [%s]" %
-> 1320                                (key, self.obj._get_axis_name(axis)))
   1321 
   1322             try:

KeyError: 'the label [0] is not in the [index]'

**Comment by ejolly** [comment]
Looks like this might be because `new.Y = self.Y.loc[index]` in `__getitem__` should use `.iloc` instead of `.loc`. Recent versions of Pandas raise KeyError Exceptions if `.loc` is not strictly a label. 
`.ix` is also an option for agnostic label/integer based indexing.

**Comment by ljchang** [comment]
good call @ejolly, switching to iloc from loc seems like it fixed the issue.
