### ISSUE TITLE
TypeError: create_cov_data() got an unexpected keyword argument 'radius'

### ISSUE THREAD

**Issue by burnash** [ljchang/neurolearn#28]
It looks like the `radius` argument is missing in [`Simulator.create_cov_data()`](https://github.com/ljchang/neurolearn/blob/a560ba8a457a611916ca6b6070515dbfe1ba2ede/nltools/simulator.py#L224) definition.

This causes a TypeError when running the NLTools_Brain_Data_Class_Tutorial:

![screen shot 2016-02-21 at 22 33 48](https://cloud.githubusercontent.com/assets/264674/13204856/3d1f4544-d8eb-11e5-9be3-99a31d4de859.png)

**Comment by ljchang** [comment]
@burnash sorry about that.  @samjgrey3 was adding some new features to that class, but got busy with his coursework and hasn't finished yet.  @samjgrey3 do you mind developing new things on a separate fork so that you don't break all of the other projects that depend on these functions?  We can add them as pull requests and make sure that all of our tests still work.

**Comment by ljchang** [comment]
@burnash: I just looked at the code and I think you can omit the radius argument for now.  We are moving towards inputting a mask that can be more flexible than just a sphere.  

Here is an example for how to create a spherical mask that can be input into the function.

s1 = create_sphere([41, 64, 55], radius=10)

sim.create_cov_data(cor, cov, sigma, mask=s1, reps = reps, n_sub = n_sub, output_dir = output_dir)

**Comment by burnash** [comment]
@ljchang Thanks for the snippet. I'll try it.

**Comment by burnash** [comment]
For the git branching model, I think something simple like [GitHub Flow](https://guides.github.com/introduction/flow/) will do. We might as well introduce a 'develop' branch for non production-ready code.

**Comment by burnash** [comment]
@ljchang got it all working now with your fixes (excluding [Bootstrap Brain_Data Analysis Methods](http://nbviewer.jupyter.org/github/ljchang/neurolearn/blob/master/scripts/NLTools_Brain_Data_Class_Tutorial.ipynb#Bootstrap-Brain_Data-Analysis-Methods) which seems to fail in the original notebook as well; and Decompose Spatial Image because I miss those nifti source files, but I guess it's unrelated to my task.)

**Comment by ljchang** [comment]
great! there is an open issue for the bootstrap method error.  The decompose spatial image works, but needs better documentation and isn't necessary for the website.

**Comment by burnash** [comment]
Sorry, I overlooked the bootstrap issue.
