### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'Test_Brain_Data/centered_sphere_cor0.8_cov0.6_sigma0.5.nii.gz'

### ISSUE THREAD

**Issue by burnash** [ljchang/neurolearn#30]
NLTools_Brain_Data_Class_Tutorial fails with: `IOError: [Errno 2] No such file or directory: 'Test_Brain_Data/centered_sphere_cor0.8_cov0.6_sigma0.5.nii.gz'` in

![screen shot 2016-02-21 at 23 53 05](https://cloud.githubusercontent.com/assets/264674/13205297/5c521e40-d8f6-11e5-9a0e-ea1585191321.png)

I guess this is because the output file prefix was changed to `maskdata_cor` in https://github.com/ljchang/neurolearn/commit/43d58892fb18017f18bae13dc0c80173320929db.

**Comment by ljchang** [comment]
You're right, looks like the name changed in the new code.  I updated the ipython notebook to address both of the errors you discovered

**Comment by burnash** [comment]
Thanks @ljchang
