### ISSUE TITLE
TypeError in Brain_Data.similarity when the image is a Nifti1Image instance

### ISSUE THREAD

**Issue by burnash** [ljchang/neurolearn#32]
`Brain_Data.similarity()` fails with TypeError if the `image` argument a Nifti1Image instance.

It looks like for Nifti1Image objects `.shape` is a tuple:

~~~python
        if not isinstance(image, Brain_Data):
            if isinstance(image, nib.Nifti1Image):
                image = self.nifti_masker.fit_transform(image)
            else:
                raise ValueError("Image is not a Brain_Data or nibabel instance")
>       dim = image.shape()
E       TypeError: 'tuple' object is not callable
~~~

**Comment by ljchang** [comment]
@burnash: Good catch! I changed it so that it just converts image to a Brain_Data() instance.  not sure why I didn't do that in the first place.

**Comment by burnash** [comment]
@ljchang thanks for the fix!
