### ISSUE TITLE
KeyError  'dist_from_hyperplane_xval' in nltools.data

### ISSUE THREAD

**Issue by burnash** [ljchang/neurolearn#33]
I'm getting `KeyError  'dist_from_hyperplane_xval'` while using RidgeClassifier:

~~~python
                    if predictor_settings['algorithm'] not in ['svm','ridgeClassifier','ridgeClassifierCV']:
                        output['prob_xval'][test] = predictor_cv.predict_proba(self.data[test])
                    else:
->                      output['dist_from_hyperplane_xval'][test] = predictor_cv.decision_function(self.data[test])
                        if predictor_settings['algorithm'] == 'svm' and predictor_cv.probability:
                            output['prob_xval'][test] = predictor_cv.predict_proba(self.data[test])
~~~

It looks like [`output['dist_from_hyperplane_xval']`](https://github.com/ljchang/neurolearn/blob/f1e7036cd6ad17ea46b42679c6d0b1a60731f375/nltools/data.py#L556) is not defined. Maybe this should be [`dist_from_hyperplane_xval`](https://github.com/ljchang/neurolearn/blob/f1e7036cd6ad17ea46b42679c6d0b1a60731f375/nltools/data.py#L545)?

**Comment by ljchang** [comment]
It looks like there were some issues with a few of the classification steps.  I think I caught all of them for now.  I also turned off plotting for classification.  I think I'd like to add ROC analyses, but didn't have time to finish that tonight.  It doesn't really matter for the website as you are currently not using the matplotlib plots anyway.

**Comment by burnash** [comment]
Thanks for the fix.
