### ISSUE TITLE
Issue with svr & loso cross-validation

### ISSUE THREAD

**Issue by jmol048** [ljchang/neurolearn#38]
Running:
output = dat.predict(algorithm='svr', cv_dict={'type': 'loso', 'subject_id': holdout}, plot=False,**{'kernel':"linear"}

Returns this error:
TypeError                                 Traceback (most recent call last)
<ipython-input-63-60283ac12348> in <module>()
      1 dat.Y = Y
      2 print holdout
----> 3 output = dat.predict(algorithm='svr', cv_dict={'type': 'loso', 'subject_id': holdout}, plot=False,**{'kernel':"linear"})
      4 
      5 # Display the available data in the output dictionary

/data/projects/oreillylab/jessica/anaconda/lib/python2.7/site-packages/nltools-0.2-py2.7.egg/nltools/data.pyc in predict(self, algorithm, cv_dict, plot, **kwargs)
    529 
    530         # Set algorithm
--> 531         if algorithm is not None:
    532             predictor_settings = set_algorithm(algorithm, **kwargs)
    533         else:

/data/projects/oreillylab/jessica/anaconda/lib/python2.7/site-packages/nltools-0.2-py2.7.egg/nltools/cross_validation.pyc in set_cv(cv_dict)
    206             from nltools.cross_validation import LeaveOneSubjectOut
    207             cv = LeaveOneSubjectOut(len(cv_dict['subject_id']), labels=cv_dict['subject_id'])
--> 208         else:
    209             raise ValueError("""Make sure you specify a dictionary of
    210             {'type': 'kfolds', 'n_folds': n},

/data/projects/oreillylab/jessica/anaconda/lib/python2.7/site-packages/nltools-0.2-py2.7.egg/nltools/cross_validation.pyc in __init__(self, n, labels, shuffle, random_state)
    146     def __init__(self, n, labels, shuffle=False, random_state=None):
    147         super(LeaveOneSubjectOut, self).__init__(n, len(np.unique(labels)), shuffle, random_state)
--> 148         self.idxs = np.arange(len(labels))
    149         self.labels = np.array(labels, copy=True)
    150         self.n_subs = len(np.unique(self.labels))

TypeError: __init__() takes exactly 6 arguments (5 given)

dat.Y is an array of category labels for each image (1 or 2), and holdout is the subject id for each image.

**Comment by ljchang** [comment]
@jmol048 Try updating to the latest version.  That code looks outdated.

**Comment by jmol048** [comment]
Thanks! Do you have tips on the best way to update to the latest (and check my current version)? I have tried deleting and cloning the git directory and running the setup.py script, but I seem to be getting the same result.

**Comment by ljchang** [comment]
I can't seem to replicate your errror.

```python
output = dat.predict(algorithm='svr', cv_dict={'type': 'loso', 'subject_id': holdout}, plot=False,**{'kernel':"linear"})
```
works fine for me.

One other thing is to check your version of other dependencies.  Scikit-learn changed some of the cross-validation API a few versions ago. 

Can you run a `pip freeze` ?

**Comment by jmol048** [comment]
Here is the output of pip freeze. I upgraded scikit-learn and reinstalled neurolearn, but am still seeing the error. 

pip freeze
You are using pip version 6.0.8, however version 8.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
abstract-rendering==0.5.1
argcomplete==0.8.4
astropy==1.0.1
backports.ssl-match-hostname==3.4.0.2
bcolz==0.8.1
beautifulsoup4==4.3.2
binstar==0.10.1
bitarray==0.8.1
blaze==0.7.3
blz==0.6.2
bokeh==0.8.1
boto==2.36.0
cdecimal==2.3
certifi==14.5.14
cffi==0.9.2
clyent==0.3.4
colorama==0.3.3
conda==3.10.0
conda-build==1.11.0
conda-env==2.1.3
configobj==5.0.6
cryptography==0.8
Cython==0.22
cytoolz==0.7.2
DataShape==0.4.4
decorator==3.4.0
docutils==0.12
enum34==1.0.4
fastcache==1.0.2
Flask==0.10.1
funcsigs==0.4
futures==2.2.0
gevent==1.0.1
gevent-websocket==0.9.3
greenlet==0.4.5
grin==1.2.1
h5py==2.4.0
ipython==3.0.0
itsdangerous==0.24
jdcal==1.0
jedi==0.8.1
Jinja2==2.7.3
jsonschema==2.4.0
llvmlite===0.2.2-1-gbcb15be
lxml==3.4.2
MarkupSafe==0.23
matplotlib==1.4.3
mistune==0.5.1
mock==1.0.1
multipledispatch==0.4.7
networkx==1.9.1
neurosynth==0.3.3
nibabel==2.0.0
nilearn==0.1.3
nipy==0.4.0
nltk==3.0.2
nltools==0.2
nose==1.3.4
numba==0.17.0
numexpr==2.3.1
numpy==1.9.2
odo==0.3.1
openpyxl==1.8.5
pandas==0.15.2
patsy==0.3.0
pep8==1.6.2
Pillow==2.7.0
ply==3.4
psutil==2.2.1
ptyprocess==0.4
py==1.4.26
pyasn1==0.1.7
pycosat==0.6.1
pycparser==2.10
pycrypto==2.6.1
pycurl==7.19.5.1
pyflakes==0.8.1
Pygments==2.0.2
pyOpenSSL==0.14
pyparsing==2.0.3
pytest==2.6.4
python-dateutil==2.4.1
pytz==2015.2
PyYAML==3.11
pyzmq==14.5.0
redis==2.10.3
requests==2.6.0
rope==0.9.4
runipy==0.1.3
scikit-image==0.11.2
scikit-learn==0.17.1
scipy==0.15.1
seaborn==0.5.1
six==1.9.0
sockjs-tornado==1.0.1
Sphinx==1.2.3
spyder==2.3.4
SQLAlchemy==0.9.9
statsmodels==0.6.1
sympy==0.7.6
tables==3.1.1
terminado==0.5
Theano==0.6.0
toolz==0.7.1
tornado==4.1
ujson==1.33
unicodecsv==0.9.4
Werkzeug==0.10.1
xlrd==0.9.3
XlsxWriter==0.6.7
xlwt==0.7.5

**Comment by ljchang** [comment]
you have a bunch of outdated dependencies for scikit-learn.  I wonder if that is affecting anything.

I'm not sure that this is the source of the problem, but I can't think of much else and the only problem we've ever run into regarding cross-validation has been the sklearn API change in version 17.

maybe run a `pip list --outdated` or `conda update --all`  

Also, this is stupid, but you are restarting your ipython kernel after reinstalling everything right?

**Comment by jmol048** [comment]
Thanks! It worked after a conda update --all. Must have been the old scikit dependencies.
