### ISSUE TITLE
AttributeError when Brain_Data receives Nifti image as an argument

### ISSUE THREAD

**Issue by burnash** [ljchang/neurolearn#43]
When Brain_Data is initialized with Nifti image as its `data` argument, the exception is raised: `AttributeError: 'Brain_Data' object has no attribute 'data'`. 

For example, this happens when I try to calculate similarity Brain_Data instance and Nibabel image:

~~~python
  File "nlweb/analysis.py", line 151, in apply_mask
    r = dat.similarity(weight_map)
  File "lib/python2.7/site-packages/nltools/data.py", line 413, in similarity
    image = Brain_Data(image)
  File "lib/python2.7/site-packages/nltools/data.py", line 85, in __init__
    if any([x==1 for x in self.data.shape]):
AttributeError: 'Brain_Data' object has no attribute 'data'
~~~

It looks like `self.data` does not get initialized when `data` argument to `Brain_Data.__init__()` is a Nifty image.

**Comment by ljchang** [comment]
Must have gotten introduced when we fixed the loading images from a list issue.

Fixed and added new tests.
